CONTAINER AINODE_BERCONWOOD
{
    NAME ainode_BerconWood;

    GROUP C4DAI_BERCONWOOD_MAIN_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_BERCONWOOD_COLOR_1 {}
        AIPARAM C4DAIP_BERCONWOOD_COLOR_2 {}
        AIPARAM C4DAIP_BERCONWOOD_WOOD_TYPE {}
        AIPARAM C4DAIP_BERCONWOOD_SEED {}
        AIPARAM C4DAIP_BERCONWOOD_SIZE {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_BERCONWOOD_LOW_THRESHOLD {}
        AIPARAM C4DAIP_BERCONWOOD_HIGH_THRESHOLD {}
        AIPARAM C4DAIP_BERCONWOOD_SKEW {}
        AIPARAM C4DAIP_BERCONWOOD_WIDTH_VARIATION {}
        AIPARAM C4DAIP_BERCONWOOD_GAIN_VARIATION {}
    }

    GROUP C4DAI_BERCONWOOD_TRUNK_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_BERCONWOOD_TRUNK_WOBBLE_STRENGTH {}
        AIPARAM C4DAIP_BERCONWOOD_TRUNK_WOBBLE_FREQUENCY {}
    }

    GROUP C4DAI_BERCONWOOD_RADIAL_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_BERCONWOOD_RADIAL_STRENGTH {}
        AIPARAM C4DAIP_BERCONWOOD_RADIAL_FREQUENCY {}
        AIPARAM C4DAIP_BERCONWOOD_RADIAL_Z_FREQUENCY {}
    }

    GROUP C4DAI_BERCONWOOD_ANGULAR_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_BERCONWOOD_ANGULAR_STRENGTH {}
        AIPARAM C4DAIP_BERCONWOOD_ANGULAR_FREQUENCY {}
        AIPARAM C4DAIP_BERCONWOOD_ANGULAR_RADIUS {}
    }

    GROUP C4DAI_BERCONWOOD_GRAIN_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_BERCONWOOD_COLOR_GRAIN {}
        AIPARAM C4DAIP_BERCONWOOD_GRAIN_STRENGTH {}
        AIPARAM C4DAIP_BERCONWOOD_GRAIN_FREQUENCY {}
    }

    GROUP C4DAI_BERCONWOOD_COORDINATES_GRP
    {
        AIPARAM C4DAIP_BERCONWOOD_SPACE {}
        AIPARAM C4DAIP_BERCONWOOD_OFFSET {}
        AIPARAM C4DAIP_BERCONWOOD_SCALE {}
        AIPARAM C4DAIP_BERCONWOOD_ROTATE {}
        AIPARAM C4DAIP_BERCONWOOD_P {}
        SEPARATOR {LINE;}
        STRING C4DAIP_BERCONWOOD_INFO { READONLY; ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; }
    }
}

